version: '3.8'

services:
  mate-backend:
    build: .                 # 让 Docker 自动寻找当前目录的 Dockerfile 进行构建
    container_name: mate_app
    restart: always
    ports:
      - "80:5000"            # 将服务器的 80 端口（默认 HTTP 端口）映射到容器的 5000 端口
    depends_on:
      - mysql
      - redis
    volumes:
      - mate_uploads:/app/uploads # 持久化用户上传的图片

  mysql:
    image: mysql:8.0
    container_name: mate_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mate_db
    command: --default-authentication-plugin=mysql_native_password --max_connections=200
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: mate_redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
  mate_uploads: